### ISSUE TITLE
Bot Stuck in state: Initializing WebSocket

### ISSUE THREAD

**Issue by LordOberlord** [verata-veritatis/bybit-market-maker#2]
Even after 30 mins the bot could not overcome the state of Initializing WebSocket.

**Comment by verata-veritatis** [comment]
Are you getting “Authorization Successful” message?

**Comment by verata-veritatis** [comment]
@LordOberlord I've been able to recreate the problem by leaving the API key/secret fields on `settings.py` blank. Please confirm you have your keys in there.

**Comment by verata-veritatis** [comment]
Added notification for failed authorization so user knows to retry in `pybit` commit e378861049fea5322f2e2fdd31d73e567299195d

**Comment by LordOberlord** [comment]
I changed in settings.py:
TEST_NET = False
API_KEY = 'N2lMZ9zir...'
PRIVATE_KEY = 'Y4tpzd7KiJbdJU...'

My log:
2020-04-07 00:25:11 - pybit - INFO - Initializing HTTP session.
2020-04-07 00:25:11 - pybit - INFO - Initializing WebSocket.

I got no further Messages.

**Comment by verata-veritatis** [comment]
Yeah I'm looking into it. I haven't updated the PyPI repo yet so you'd have to manually edit your __init__.py file. I'll run updates tonight so you can `pip install --upgrade pybit`.

**Comment by LordOberlord** [comment]
I am now able to start the bot.
