### ISSUE TITLE
does get_last_price() refer to the bid or the ask?

### ISSUE THREAD

**Issue by metaperl** [verata-veritatis/bybit-market-maker#4]
On [this line](https://github.com/verata-veritatis/bybit-market-maker/blob/master/market_maker/market_maker.py#L119) is a call to [get_last_price](https://github.com/verata-veritatis/bybit-market-maker/blob/master/market_maker/market_maker.py#L94) ... 

is price the bid or ask?

**Comment by verata-veritatis** [comment]
Last price is the price of the last trade. I've been working on making significant upgrades to pybit, so I'll be updating the market-maker as well.
